logging:
    level:
        org:
            springframework:
                ws: ERROR

management:
    endpoints:
        web:
            exposure:
                include: '*'

spring:

    devtools:
        restart:
            additional-paths: /resources
        